spring.application.name=telecom-device-manager
spring.devtools.restart.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-stacktrace=never

security.api-key.header=X-API-KEY
security.api-key.value=telecom-dev-key-321
